/**
 * `@fudic/diagnostics` — every fudic diagnostic. One code, one file, one typed function; the
 * folder `codes/` IS the catalogue. Everything is re-exported here and the package declares
 * `"sideEffects": false`, so a bundle only keeps the codes it calls.
 */

export type {
  Severity,
  FudCode,
  RelatedLocation,
  SourceDiagnostic,
  FileDiagnostic,
  ProjectDiagnostic,
  FudDiagnostic,
  SourceInput,
  FileInput,
} from './types.js';
export type { Span } from './span.js';
export { span, emptySpan, spanLength, isEmptySpan, mergeSpans, spanContains } from './span.js';
export type { Position, Range } from './position.js';
export { LineMap, rangeOf } from './linemap.js';
export type { Place, Rendered, FormatOptions } from './render.js';
export { render, format } from './render.js';
export { DOCS_BASE, docsUrl } from './docs.js';

// ── codes ──────────────────────────────────────────────────────────────────────
export * from './codes/FUD0001.js';
export * from './codes/FUD0002.js';
export * from './codes/FUD0003.js';
export * from './codes/FUD0004.js';
export * from './codes/FUD0005.js';
export * from './codes/FUD0006.js';
export * from './codes/FUD0007.js';
export * from './codes/FUD0010.js';
export * from './codes/FUD0011.js';
export * from './codes/FUD0012.js';
export * from './codes/FUD0013.js';
export * from './codes/FUD0014.js';
export * from './codes/FUD0015.js';
export * from './codes/FUD0016.js';
export * from './codes/FUD0051.js';
export * from './codes/FUD0052.js';
export * from './codes/FUD0053.js';
export * from './codes/FUD0054.js';
export * from './codes/FUD0055.js';
export * from './codes/FUD0056.js';
export * from './codes/FUD0057.js';
export * from './codes/FUD0070.js';
export * from './codes/FUD0071.js';
export * from './codes/FUD0072.js';
export * from './codes/FUD0073.js';
export * from './codes/FUD0074.js';
export * from './codes/FUD0075.js';
export * from './codes/FUD0091.js';
export * from './codes/FUD0092.js';
export * from './codes/FUD0093.js';
export * from './codes/FUD0094.js';
export * from './codes/FUD0095.js';
export * from './codes/FUD0096.js';
export * from './codes/FUD0097.js';
export * from './codes/FUD0098.js';
export * from './codes/FUD0099.js';
export * from './codes/FUD0110.js';
export * from './codes/FUD0111.js';
export * from './codes/FUD0114.js';
export * from './codes/FUD0131.js';
export * from './codes/FUD0132.js';
export * from './codes/FUD0150.js';
export * from './codes/FUD0151.js';
export * from './codes/FUD0152.js';
export * from './codes/FUD0153.js';
export * from './codes/FUD0154.js';
export * from './codes/FUD0155.js';
export * from './codes/FUD0156.js';
export * from './codes/FUD0157.js';
export * from './codes/FUD0158.js';
export * from './codes/FUD0159.js';
export * from './codes/FUD0160.js';
export * from './codes/FUD0161.js';
export * from './codes/FUD0170.js';
export * from './codes/FUD0190.js';
export * from './codes/FUD0191.js';
export * from './codes/FUD0192.js';
export * from './codes/FUD0193.js';
export * from './codes/FUD0194.js';
export * from './codes/FUD0195.js';
export * from './codes/FUD0196.js';
export * from './codes/FUD0197.js';
export * from './codes/FUD0198.js';
export * from './codes/FUD0199.js';
export * from './codes/FUD0200.js';
export * from './codes/FUD0201.js';
export * from './codes/FUD0202.js';
export * from './codes/FUD0203.js';
export * from './codes/FUD0290.js';
export * from './codes/FUD0291.js';
export * from './codes/FUD0294.js';
export * from './codes/FUD0360.js';
export * from './codes/FUD0361.js';
export * from './codes/FUD0362.js';
export * from './codes/FUD0363.js';
export * from './codes/FUD0364.js';
export * from './codes/FUD0365.js';
export * from './codes/FUD0366.js';
export * from './codes/FUD0390.js';
export * from './codes/FUD0391.js';
export * from './codes/FUD0392.js';
export * from './codes/FUD0393.js';
export * from './codes/FUD0394.js';
export * from './codes/FUD0396.js';
export * from './codes/FUD0397.js';
export * from './codes/FUD0398.js';
export * from './codes/FUD0399.js';
export * from './codes/FUD0420.js';
export * from './codes/FUD0421.js';
export * from './codes/FUD0423.js';
export * from './codes/FUD0424.js';
export * from './codes/FUD0425.js';
export * from './codes/FUD0426.js';
export * from './codes/FUD0427.js';
export * from './codes/FUD0428.js';
export * from './codes/FUD0429.js';
export * from './codes/FUD0430.js';
export * from './codes/FUD0431.js';
export * from './codes/FUD0432.js';
export * from './codes/FUD0433.js';
export * from './codes/FUD0434.js';
export * from './codes/FUD0435.js';
export * from './codes/FUD0436.js';
export * from './codes/FUD0438.js';
export * from './codes/FUD0439.js';
export * from './codes/FUD0440.js';
export * from './codes/FUD0441.js';
export * from './codes/FUD0442.js';
export * from './codes/FUD0443.js';
export * from './codes/FUD0444.js';
export * from './codes/FUD0445.js';
export * from './codes/FUD0446.js';
export * from './codes/FUD0447.js';
export * from './codes/FUD0448.js';
export * from './codes/FUD0449.js';
export * from './codes/FUD0450.js';
export * from './codes/FUD0451.js';
export * from './codes/FUD0460.js';
export * from './codes/FUD0461.js';
export * from './codes/FUD0480.js';
export * from './codes/FUD0481.js';
export * from './codes/FUD0482.js';
export * from './codes/FUD0500.js';
export * from './codes/FUD0501.js';
export * from './codes/FUD0540.js';
export * from './codes/FUD0541.js';
export * from './codes/FUD0542.js';
export * from './codes/FUD0543.js';
export * from './codes/FUD0570.js';
export * from './codes/FUD0590.js';
export * from './codes/FUD0591.js';
export * from './codes/FUD0592.js';
export * from './codes/FUD0593.js';
export * from './codes/FUD0594.js';
export * from './codes/FUD0595.js';
export * from './codes/FUD0596.js';
export * from './codes/FUD0597.js';
export * from './codes/FUD0598.js';
export * from './codes/FUD0599.js';
export * from './codes/FUD0600.js';
export * from './codes/FUD0601.js';
export * from './codes/FUD0602.js';
export * from './codes/FUD0605.js';
export * from './codes/FUD0620.js';
export * from './codes/FUD0621.js';
export * from './codes/FUD0622.js';
export * from './codes/FUD0660.js';
export * from './codes/FUD0661.js';
export * from './codes/FUD0662.js';
export * from './codes/FUD0663.js';
export * from './codes/FUD0664.js';
export * from './codes/FUD0665.js';
export * from './codes/FUD0666.js';
export * from './codes/FUD0667.js';
export * from './codes/FUD0680.js';
export * from './codes/FUD0681.js';
export * from './codes/FUD0682.js';
export * from './codes/FUD0683.js';
export * from './codes/FUD0684.js';
export * from './codes/FUD0700.js';
export * from './codes/FUD0701.js';
export * from './codes/FUD0702.js';
export * from './codes/FUD0705.js';
export * from './codes/FUD0720.js';
export * from './codes/FUD0721.js';
export * from './codes/FUD0724.js';
export * from './codes/FUD0725.js';
export * from './codes/FUD0726.js';
export * from './codes/FUD0740.js';
export * from './codes/FUD0741.js';
export * from './codes/FUD0742.js';
export * from './codes/FUD0743.js';
export * from './codes/FUD0744.js';
export * from './codes/FUD0745.js';
export * from './codes/FUD0760.js';
export * from './codes/FUD0761.js';
export * from './codes/FUD0763.js';
export * from './codes/FUD0780.js';
export * from './codes/FUD0781.js';
export * from './codes/FUD0782.js';
export * from './codes/FUD0783.js';
export * from './codes/FUD0784.js';
export * from './codes/FUD0785.js';
export * from './codes/FUD0800.js';
export * from './codes/FUD0801.js';
export * from './codes/FUD0802.js';
export * from './codes/FUD0803.js';
export * from './codes/FUD0804.js';
export * from './codes/FUD0805.js';
export * from './codes/FUD0806.js';
export * from './codes/FUD0820.js';
export * from './codes/FUD0821.js';
export * from './codes/FUD0822.js';
export * from './codes/FUD0823.js';
export * from './codes/FUD0824.js';
export * from './codes/FUD0825.js';
export * from './codes/FUD0826.js';
export * from './codes/FUD0827.js';
export * from './codes/FUD0828.js';
export * from './codes/FUD0829.js';
export * from './codes/FUD0830.js';
export * from './codes/FUD0831.js';
export * from './codes/FUD0832.js';
export * from './codes/FUD0834.js';
export * from './codes/FUD0835.js';
export * from './codes/FUD0836.js';
export * from './codes/FUD0850.js';
export * from './codes/FUD0851.js';
export * from './codes/FUD0852.js';
export * from './codes/FUD0853.js';
export * from './codes/FUD0854.js';
export * from './codes/FUD0855.js';
export * from './codes/FUD0856.js';
export * from './codes/FUD0857.js';
export * from './codes/FUD0858.js';
export * from './codes/FUD0890.js';
export * from './codes/FUD0891.js';
export * from './codes/FUD0892.js';
export * from './codes/FUD0893.js';
export * from './codes/FUD0894.js';
export * from './codes/FUD0895.js';
