/**
 * Criterion 13 — a workspace generated by these commands BUILDS, and the library's component
 * comes out in the app's HTML.
 *
 * Everything below is written by the commands themselves, against a real temporary directory:
 * `fudic new --workspace`, then `fudic g lib`, then `fudic g app --uses`, then
 * `fudic g component --project ui --in <the app's route>`. Nothing is hand-placed, because a
 * hand-placed file would be evidence about a tree no user will ever have.
 *
 * `pnpm install` is replaced by workspace aliases, exactly as `new-build.test.ts` does it and
 * for the same reason: the generated `package.json` asks for `@fudic/*` at their real
 * versions and none of them is on npm, so a real install dies with a 404.
 *
 * **What that substitution cannot see, and it cost a bug.** An alias resolves a specifier
 * from anywhere, so this build is blind to WHICH package declares a dependency. Run for real
 * against `scripts/local-registry.mjs`, the same workspace failed: the client chunk of the
 * library's component imports `@fudic/core`, that import resolves from the library, and the
 * library did not declare it. `projects.test.ts` now asserts the dependency directly, which is
 * the guard this file structurally cannot provide. The literal `pnpm install && pnpm build`
 * lives behind `pnpm registry`, and it is worth running whenever the generated
 * `package.json`s change.
 *
 * This is the point where SDD-44 touches SDD-43: if resolution across packages were not there,
 * this test says so instead of leaving it for the day of a deployment.
 */

import { describe, expect, it, beforeAll } from 'vitest';
import { build } from 'vite';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { fudic } from '@fudic/vite';
import { planWorkspace } from '../../src/plans/workspace.js';
import { planApp } from '../../src/plans/app.js';
import { planLib } from '../../src/plans/lib.js';
import { planComponent } from '../../src/plans/component.js';
import { apply } from '../../src/apply.js';
import { nodeReadIo, nodeWriteIo } from '../../src/io.js';
import { RecordingRunner } from '../helpers.js';
import type { Plan } from '../../src/types.js';

const ssrDist = fileURLToPath(new URL('../../../ssr/dist/index.js', import.meta.url));
const transportDist = fileURLToPath(new URL('../../../transport/dist/index.js', import.meta.url));
const coreDist = fileURLToPath(new URL('../../../core/dist/index.js', import.meta.url));

describe('a generated workspace builds (criterion 13)', () => {
  let output: { fileName: string; code?: string; source?: string }[];
  let ws: string;
  let appPkg: Record<string, unknown>;

  beforeAll(async () => {
    const tmp = mkdtempSync(join(tmpdir(), 'fudic-ws-'));
    const io = nodeReadIo();
    const write = nodeWriteIo();
    const runner = new RecordingRunner();

    /** Apply a plan that must have produced no errors, and say which command failed if it did. */
    const run = async (label: string, plan: Plan, cwd: string): Promise<void> => {
      expect(plan.errors.map((error) => `${error.code} ${error.message}`), label).toEqual([]);
      await apply(plan, { cwd, force: false }, write, runner);
    };

    // 1. The workspace and its first app.
    await run(
      'fudic new mi-tienda --workspace --app web',
      await planWorkspace(
        'mi-tienda',
        {
          cwd: tmp, force: false, app: 'web', id: 'web', prefix: 'web',
          pm: 'pnpm', install: false, git: false, sw: true, layout: '_layout', target: 'static',
        },
        io,
      ),
      tmp,
    );
    ws = join(tmp, 'mi-tienda');

    // 2. The library.
    await run(
      'fudic g lib ui --prefix ui',
      await planLib('ui', { cwd: ws, force: false, dir: 'libs', prefix: 'ui', uses: [] }, io),
      ws,
    );

    // 3. A second app that declares the dependency, which is what `--uses` is for.
    await run(
      'fudic g app back --uses ui',
      await planApp(
        'back',
        { cwd: ws, force: false, dir: 'apps', prefix: 'bk', uses: ['ui'], id: 'back', sw: false },
        io,
      ),
      ws,
    );

    // 4. The library's component, wired into the FIRST app's route in the same command. The
    //    href it writes is what the build has to follow across the package boundary.
    await run(
      'fudic g component card --project ui --in apps/web/src/routes/index.fud',
      await planComponent(
        'card',
        {
          cwd: ws, force: false, dir: 'src/components', project: 'ui',
          wireInto: ['apps/web/src/routes/index.fud'], style: true, slot: true,
        },
        io,
      ),
      ws,
    );

    expect(runner.commands, 'no command was asked for, so none ran').toEqual([]);

    // 5. The one line the AUTHOR writes. `--in` wires the `<link rel="component">`; which
    //    component a piece of markup uses is not the CLI's call (§4.7), so using the tag is
    //    a person typing it into their route — done here exactly as they would.
    const route = join(ws, 'apps/web/src/routes/index.fud');
    const source = io.read(route);
    expect(source, 'the link across the package boundary').toContain('rel="component"');
    write.write(route, `${source}<ui-card>from the library</ui-card>\n`);

    appPkg = JSON.parse(io.read(join(ws, 'apps/back/package.json'))) as Record<string, unknown>;

    const result = (await build({
      root: join(ws, 'apps/web'),
      logLevel: 'silent',
      // The generated `vite.config.ts` is not loaded, for the reason the header gives: its own
      // `vite` and `@fudic/vite` imports would need the install this test replaces. Its content
      // is asserted separately.
      configFile: false,
      resolve: {
        alias: { '@fudic/ssr': ssrDist, '@fudic/transport': transportDist, '@fudic/core': coreDist },
      },
      plugins: [fudic()],
      build: { write: false, minify: false },
    })) as unknown as { output: { fileName: string; code?: string; source?: string }[] };
    output = result.output;
  }, 180_000);

  it('prerenders the app, with the LIBRARY component in its HTML', () => {
    const html = output.find((file) => file.fileName === 'index.html');
    expect(html, output.map((file) => file.fileName).join(', ')).toBeDefined();

    const text = String(html!.source);
    expect(text).toContain('<!DOCTYPE html>');
    // The component defined in `libs/ui`, rendered inside the app of `apps/web`, with its
    // shadow root inlined. The declarative template is what makes this the criterion rather
    // than a test of a string I typed: it is only there if the compiler followed the href
    // across the package boundary, read the library's `.fud` and serialized it.
    expect(text).toMatch(/<ui-card><template shadowrootmode=/u);
  });

  it('emits the client chunk of the library component', () => {
    expect(output.some((file) => /^assets\/h\/ui-card-.*\.js$/u.test(file.fileName))).toBe(true);
  });

  it('wrote the dependency as workspace:*, and no link for it', () => {
    expect(appPkg['dependencies']).toMatchObject({ '@mi-tienda/ui': 'workspace:*' });
  });
});
