/**
 * The ambient declarations, mounted in memory (SDD-24 §2).
 *
 * `GLOBALS_DTS` is the text the projection of SDD-23 is written against — `$text`, `$attrs`,
 * `$section`, `props<T>()`. The CLI writes it to disk so `tsc` and CI see what the editor sees;
 * the server mounts the same constant as a file of the program, so the LSP also works in a
 * project that never ran `fudic new`. One source, two consumers.
 *
 * When the file DOES exist on disk it declares exactly the same names, so mounting it again
 * would be a program with two of everything — TS2300 on every identifier. Hence the check: this
 * is a fallback, not a duplicate.
 */

import { GLOBALS_DTS, GLOBALS_FILE_NAME } from '@fudic/language-core';
import type * as ts from 'typescript';
import { snapshotOf } from './virtual-code.js';

export { GLOBALS_DTS, GLOBALS_FILE_NAME };

/**
 * Make the ambient declarations of THIS server the ones the project typechecks against.
 *
 * Patches the host in place: the object belongs to Volar's project, which hands it over live,
 * and wrapping it in a proxy would lose the methods Volar adds afterwards.
 *
 * Returns whether a file had to be added to the program, which is what the log line reports.
 * A project that already lists one gets its CONTENT replaced instead, and that is the point
 * below.
 */
export function mountGlobals(host: ts.LanguageServiceHost, root: string): boolean {
  const snapshot = snapshotOf(GLOBALS_DTS);
  const getScriptFileNames = host.getScriptFileNames.bind(host);
  const getScriptSnapshot = host.getScriptSnapshot.bind(host);
  const getScriptVersion = host.getScriptVersion.bind(host);
  // `fileExists` and `readFile` are required members of the host, so there is no absent case
  // to defend against — TypeScript itself would not accept a host without them.
  const fileExists = host.fileExists.bind(host);
  const readFile = host.readFile.bind(host);

  // THE VERSION ON DISK DOES NOT GET A VOTE, and this is the lesson of BUG-23.
  //
  // `fudic-globals.d.ts` says "Generated by fudic. Do not edit." — it is not the user's file,
  // it is this compiler's contract with itself, and the projection that reads it ships in the
  // same package as the text. A project scaffolded months ago keeps its copy, the projection
  // grows two new names (`$props`, `$required` came with this very bug), and the copy on disk
  // no longer declares them.
  //
  // Nothing about that failure is visible. `$props<$C0>({…})` becomes a call to an undeclared
  // name, and the error lands on scaffolding no span maps back — so the file COMPILES CLEAN
  // while the object literal loses its contextual type and completion falls back to the global
  // scope, and `$required` stops reporting the required prop nobody passed. A stale `.d.ts`
  // does not break the editor loudly; it turns it off in silence.
  //
  // So the file is not consulted, only occupied: whatever path the program has for it answers
  // with the text compiled into this server.
  const owned = new Set(
    getScriptFileNames().filter((name) => name.replace(/\\/g, '/').endsWith(GLOBALS_FILE_NAME)),
  );
  const mounting = ![...owned].some((name) => fileExists(name));
  const fileName = `${root}/${GLOBALS_FILE_NAME}`;
  if (mounting) owned.add(fileName);

  // Added to the program only when the project lists none: a name that is already a root file
  // must not appear twice, or every declaration in it becomes TS2300.
  if (mounting) host.getScriptFileNames = () => [...getScriptFileNames(), fileName];
  host.getScriptSnapshot = (name) => (owned.has(name) ? snapshot : getScriptSnapshot(name));
  // A constant version: the text is compiled in, so it can never change while the server runs.
  host.getScriptVersion = (name) => (owned.has(name) ? '1' : getScriptVersion(name));
  host.fileExists = (name) => owned.has(name) || fileExists(name);
  host.readFile = (name, encoding) => (owned.has(name) ? GLOBALS_DTS : readFile(name, encoding));

  return mounting;
}
