/**
 * Regenerate `src/emit/polyfill.min.ts` from the readable constant (BUG-07 §4.3):
 *
 *     node --experimental-strip-types scripts/minify-polyfill.ts
 *
 * The style-adoption polyfill is inline in every page's `<head>`, once per page — gzip
 * compresses each file on its own, so five pages carry five full copies. It is a source
 * constant in `polyfill.ts` so it can be linted and reasoned about on its own, and that
 * stays; what does not follow is that it has to be EMITTED that way.
 *
 * Why a committed generated file and not a build step: `oxc-minify` must never become a
 * runtime dependency of `@fudic/compiler` — the emit ships to users, the minifier does
 * not. Committing the result keeps `pnpm build` as plain `tsc` and keeps `pnpm test` and
 * `pnpm typecheck` working with no codegen in front of them. What keeps it honest is a
 * TEST (`test/emit/minify.test.ts`), which re-runs this same minification and fails if
 * the committed file is stale: edit the readable polyfill, forget to re-run this, and CI
 * says so.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { minifySync } from 'oxc-minify';

const here = dirname(fileURLToPath(import.meta.url));
const sourceFile = resolve(here, '../src/emit/polyfill.ts');
const outFile = resolve(here, '../src/emit/polyfill.min.ts');

/**
 * The constant's runtime value, obtained by IMPORTING it, not by slicing the file.
 *
 * `polyfill.ts` is a JSDoc plus one `export const` — valid JS as it stands, so a data URL
 * runs it. Slicing the template literal out of the text looked simpler and was wrong: the
 * engine normalises `\r\n` to `\n` inside a template literal, so on a CRLF checkout the
 * text and the value are different strings, and the minified output would depend on which
 * machine ran this.
 */
const url = `data:text/javascript;base64,${Buffer.from(readFileSync(sourceFile, 'utf8')).toString('base64')}`;
const { STYLE_POLYFILL } = (await import(url)) as { STYLE_POLYFILL: string };

const { code, errors } = minifySync('polyfill.js', STYLE_POLYFILL);
if (errors.length > 0) {
  throw new Error(`polyfill did not minify: ${errors.map((e) => e.message).join('; ')}`);
}

writeFileSync(
  outFile,
  `/**
 * GENERATED by \`scripts/minify-polyfill.ts\` — do not edit.
 *
 * The minified form of \`STYLE_POLYFILL\`, which is what pages actually embed (BUG-07
 * §4.3). Edit the readable constant in \`polyfill.ts\` and re-run the script; the test in
 * \`test/emit/minify.test.ts\` fails while this file is stale.
 */
export const STYLE_POLYFILL_MIN = ${JSON.stringify(code)};
`,
  'utf8',
);

const saved = Math.round((1 - code.length / STYLE_POLYFILL.length) * 100);
process.stdout.write(`polyfill: ${STYLE_POLYFILL.length} -> ${code.length} bytes (-${saved}%)\n`);
