/**
 * The ambient declarations the template is projected against (SDD-23 §3.3).
 *
 * One source, two consumers: the language server mounts this text as a virtual lib, so the
 * LSP works in a project that never ran the scaffolding; the CLI writes the very same text
 * to `fudic-globals.d.ts` so `tsc` and CI see what the editor sees. If the two ever
 * diverge, the editor and the build stop agreeing — hence ONE expression evaluated once, and
 * never a per-call render. The `$GlobalAttrs` members are interpolated into it from HTML's own
 * data (see `HTML_ATTRIBUTES`), which changes nothing about that guarantee: both consumers read
 * the same constant, computed at load.
 *
 * Every identifier here starts with `$`, in line with the `$` namespace reserved to the
 * compiler. A user identifier prefixed with `$` is already a semantic error, which is what
 * guarantees this scaffolding can never collide with verbatim user code.
 *
 * The one exception is `props`, which is user-facing vocabulary, not scaffolding: the user
 * writes `props<T>()` in `@code`.
 *
 * `$slot()` and `$intoSlot(name)` are the two sides of one thing and that is why they are two
 * names: `$slot` is the marker a `<slot>` leaves INSIDE a component, `$intoSlot` is what a
 * child writes from OUTSIDE to pick the slot it goes into.
 */

import { getDefaultHTMLDataProvider } from 'vscode-html-languageservice';

/**
 * The attribute a custom element is checked against for BEING an element — READ, not written.
 *
 * A component is HTML with more in it, so what may be written on `<app-input>` without a dot is
 * what may be written on a `<div>`: nothing less. And the way to guarantee "nothing less" is not
 * to keep a good list — it is to keep NO list. This is the very data VS Code answers a `.html`
 * with, asked at runtime, so the day the specification grows an attribute the answer grows with
 * the dependency and no file here is touched.
 *
 * Measured: the provider returns the same 150 names for `div` and for `app-input` — an unknown
 * tag gets the global vocabulary, which is exactly what a custom element is to HTML. 34 plain,
 * 48 `aria-*` and 68 `on*`, and all three families are kept. Picking among them is the mistake
 * this replaces: `onclick` is HTML's, and a developer who reaches for it is not wrong, however
 * much fudic prefers `@click`.
 *
 * ONE name is dropped, and it is not a matter of taste: `slot` is checked against the PARENT's
 * `$Slots` (see `$intoSlot`), so declaring it here as a plain scalar would give up the name
 * checking and the completion that make it worth projecting at all.
 */
const HTML_ATTRIBUTES: readonly string[] = getDefaultHTMLDataProvider()
  .provideAttributes('div')
  .map((attribute) => attribute.name)
  .filter((name) => name !== 'slot');

/** `aria-checked` is no identifier, so it is written as a quoted key; `id` needs no quotes. */
const PLAIN_KEY = /^[A-Za-z_$][\w$]*$/;

/** The members of `$GlobalAttrs`, one per line, indented as the surrounding literal is. */
const HTML_ATTRIBUTE_MEMBERS = HTML_ATTRIBUTES.map(
  (name) => `  ${PLAIN_KEY.test(name) ? name : `'${name}'`}?: $Scalar;`,
).join('\n');

export const GLOBALS_DTS = `// Generated by fudic. Do not edit.
declare function props<T>(): T;

type $Scalar = string | number | boolean | bigint | null | undefined;

/**
 * The attributes an element understands for BEING an element, not for being this component.
 *
 * They live here and not in a list inside the emitter, and that is the whole of BUG-11: the
 * vocabulary HTML defines belongs with the rest of what HTML defines. The emitter does not
 * learn that \`id\` or \`data-*\` exist; it hands the object literal to a type that does.
 *
 * \`slot\` is deliberately NOT here. Its value is checked against the component's own
 * \`$Slots\`, so declaring it as a plain string would give up exactly the name checking and
 * the completion that make it worth projecting at all.
 *
 * The members are GENERATED from \`HTML_ATTRIBUTES\`, which is the data VS Code answers a
 * \`.html\` with. It used to be eleven names written by hand, and eleven is what made a component
 * poorer than a \`<div>\`: a native tag is answered by the HTML service with its whole
 * vocabulary, so \`<div |>\` offered \`accesskey\` and every \`aria-*\` while \`<app-input |>\`
 * offered a curated fraction. A component is HTML with more in it, never with less.
 *
 * One list, both jobs: what is OFFERED at an empty position is enumerated from this type, and
 * what is ACCEPTED when written is checked against it. They cannot drift, because they are the
 * same sentence — the editor can never offer a name that then underlines in red.
 *
 * The index signatures stay even though every \`aria-*\` is now enumerated: enumerating is what
 * OFFERS them, the signature is what ACCEPTS the ones this version of the data has not heard of
 * yet, and a \`data-*\` is the author's own vocabulary and can never be enumerated at all.
 */
type $GlobalAttrs = {
${HTML_ATTRIBUTE_MEMBERS}
} & { [k: \`data-\${string}\`]: $Scalar } & { [k: \`aria-\${string}\`]: $Scalar };

declare function $text(v: $Scalar): void;
declare function $attr(v: $Scalar): void;
declare function $attrs<T>(a: T & $GlobalAttrs): void;

/**
 * The PROPS of a component host — what is written with a dot, and nothing else.
 *
 * Without \`$GlobalAttrs\`, and that is the whole of it (BUG-23 §2.1): the literal that
 * carries the props is the one the dot completes against, so intersecting it with HTML's
 * vocabulary made \`<app-badge .|>\` offer \`id\`, \`class\` and \`role\` beside the contract. A
 * plain attribute on the same host still goes to \`$attrs<{}>\`, which is HTML's vocabulary
 * and nothing else.
 */
declare function $props<T>(p: T): void;

/**
 * The type of an EMPTY position inside a start tag: \`<app-badge |>\`.
 *
 * Everything that may be written there, in ONE type, because the answer has to arrive in one
 * reply. A prop is written with a dot, so the key carries the dot — \`.tone\` and not \`tone\` —
 * and that is not decoration: it is what the developer types, and it is also what tells the two
 * families apart afterwards. TypeScript hands a key that is not an identifier back quoted, so
 * the props arrive as \`".tone"\` and HTML's vocabulary arrives bare, with no list kept anywhere
 * to say which is which.
 *
 * It repeals decision (b) of BUG-23 §4.0, which put HTML's vocabulary alone here and left the
 * contract behind the dot. Asking «what may go here?» and being answered \`id\`, \`class\`, \`role\`
 * is being answered the half you already knew: the props are the half that cannot be guessed.
 *
 * NOT the call that checks anything. The stretches mapped into it carry completion alone
 * (\`COMPLETION_ONLY_CAPS\`), every key is optional, and what a written attribute is checked
 * against stays \`$attrs\` — so this type can be generous without a single diagnostic depending
 * on it.
 */
declare function $gap<T>(a: { [K in keyof T & string as \`.\${K}\`]?: T[K] } & $GlobalAttrs): void;

/**
 * The REQUIRED keys of \`T\` that \`K\` does not name.
 *
 * \`-?\` strips optionality so \`Pick<T, K>\` can be compared against \`{}\`: a key that is
 * optional makes \`{}\` assignable, so it drops out and only what the author cannot forget
 * survives.
 */
type $RequiredKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? never : K }[keyof T];
type $Missing<T, K> = Pick<T, Exclude<$RequiredKeys<T>, K>>;

/**
 * Completeness, checked APART from the values (BUG-23 §2.1).
 *
 * \`TS2739\` over an object literal is reported on the whole argument — from the \`{\` to the
 * \`}\` — and both of those ends are scaffolding, so Volar mapped the error back nowhere and
 * the missing prop was never reported. Here the argument is a single stretch standing for the
 * tag NAME, which is where the author has to read it anyway.
 */
declare function $required<T, K extends PropertyKey>(rest: $Missing<T, K>): void;
declare function $on<K extends keyof HTMLElementEventMap>(
  type: K, h: (ev: HTMLElementEventMap[K]) => unknown): void;
declare function $section<T extends string>(name: T): void;
declare function $cls(v: boolean): void;
declare function $sty(v: string): void;
declare function $slot(): void;
declare function $intoSlot<T extends string>(name: T): void;
declare function $ref<E extends Element>(): E;

/**
 * A value that crosses a \`.prop\` naming a reactive — the OBJECT, or its read (decision 105).
 *
 * The build decides between the two by what the CHILD declares: a prop typed \`Signal<T>\` gets
 * the signal, one typed \`T\` gets \`name()\`. The projection cannot read the child's \`.fud\`, and
 * it does not have to — the child's contract is already imported as a type, so the question is
 * handed to the checker in the one shape that answers both at once. \`V\` is passed
 * EXPLICITLY, as the declared type of that very prop: inference from a union parameter would
 * pick the bare \`V\` branch and decide the object every time.
 *
 * That is the invariant of BUG-23 §5 kept under decision 105: where the emit transforms a
 * value before crossing it, the projection checks the same transformation — including the one
 * that transforms nothing.
 */
declare function $cross<V>(source: V | (() => V)): V;

/**
 * The declared type of ONE prop, as the value crossing into it has to satisfy it.
 *
 * Two corrections over a bare \`T[K]\`. The \`undefined\` an optional key carries is taken back
 * out: under \`exactOptionalPropertyTypes\` a \`tone?: Tone\` means «absent or Tone», so putting
 * \`Tone | undefined\` back into the literal is a \`TS2379\` about a value the author wrote
 * correctly. And a key the child does NOT declare falls back to \`unknown\` rather than to
 * \`never\`: that mistake is already reported once, on the key, and a second error about its
 * value would be the same mistake said twice.
 */
type $Prop<T, K extends PropertyKey> = K extends keyof T ? Exclude<T[K], undefined> : unknown;

/**
 * The identity of one iteration of a loop (BUG-17 §3.1).
 *
 * \`unknown\` on purpose. Offering is not validating: reconciliation keys a \`Map\`, and in a
 * \`Map\` object identity is a perfectly good key, so \`string | number\` would reject keys
 * that work. \`$key\` exists to open a scope to ask questions in, not to judge the answer.
 *
 * OPTIONAL for the same reason. A \`key (|)\` the author has not finished projects as an empty
 * argument, and that is the one moment the list is wanted; a required parameter would answer
 * it with \`TS2554\` about a stretch nobody typed. The clause being unfinished is already said,
 * once, by \`FUD0541\` — and the compiler is who owns that sentence.
 */
declare function $key(k?: unknown): void;

type $El<T extends string> = T extends keyof HTMLElementTagNameMap
  ? HTMLElementTagNameMap[T]
  : HTMLElement;
`;

/** File name the CLI writes `GLOBALS_DTS` to, and the server mounts it under. */
export const GLOBALS_FILE_NAME = 'fudic-globals.d.ts';
