/**
 * The ambient declarations the template is projected against (SDD-23 §3.3).
 *
 * One source, two consumers: the language server mounts this text as a virtual lib, so the
 * LSP works in a project that never ran the scaffolding; the CLI writes the very same text
 * to `fudic-globals.d.ts` so `tsc` and CI see what the editor sees. If the two ever
 * diverge, the editor and the build stop agreeing — hence a constant, not a template.
 *
 * Every identifier here starts with `$`, in line with the `$` namespace reserved to the
 * compiler. A user identifier prefixed with `$` is already a semantic error, which is what
 * guarantees this scaffolding can never collide with verbatim user code.
 *
 * The one exception is `props`, which is user-facing vocabulary, not scaffolding: the user
 * writes `props<T>()` in `@code`.
 */
export const GLOBALS_DTS = `// Generated by fudic. Do not edit.
declare function props<T>(): T;

type $Scalar = string | number | boolean | bigint | null | undefined;

declare function $text(v: $Scalar): void;
declare function $attr(v: $Scalar): void;
declare function $attrs<T>(a: T): void;
declare function $on<K extends keyof HTMLElementEventMap>(
  type: K, h: (ev: HTMLElementEventMap[K]) => unknown): void;
declare function $section<T extends string>(name: T): void;
declare function $cls(v: boolean): void;
declare function $sty(v: string): void;
declare function $slot(): void;
declare function $ref<E extends Element>(): E;

type $El<T extends string> = T extends keyof HTMLElementTagNameMap
  ? HTMLElementTagNameMap[T]
  : HTMLElement;
`;

/** File name the CLI writes `GLOBALS_DTS` to, and the server mounts it under. */
export const GLOBALS_FILE_NAME = 'fudic-globals.d.ts';
