/**
 * The ambient declarations the template is projected against (SDD-23 §3.3).
 *
 * One source, two consumers: the language server mounts this text as a virtual lib, so the
 * LSP works in a project that never ran the scaffolding; the CLI writes the very same text
 * to `fudic-globals.d.ts` so `tsc` and CI see what the editor sees. If the two ever
 * diverge, the editor and the build stop agreeing — hence a constant, not a template.
 *
 * Every identifier here starts with `$`, in line with the `$` namespace reserved to the
 * compiler. A user identifier prefixed with `$` is already a semantic error, which is what
 * guarantees this scaffolding can never collide with verbatim user code.
 *
 * The one exception is `props`, which is user-facing vocabulary, not scaffolding: the user
 * writes `props<T>()` in `@code`.
 *
 * `$slot()` and `$intoSlot(name)` are the two sides of one thing and that is why they are two
 * names: `$slot` is the marker a `<slot>` leaves INSIDE a component, `$intoSlot` is what a
 * child writes from OUTSIDE to pick the slot it goes into.
 */
export const GLOBALS_DTS = `// Generated by fudic. Do not edit.
declare function props<T>(): T;

type $Scalar = string | number | boolean | bigint | null | undefined;

/**
 * The attributes an element understands for BEING an element, not for being this component.
 *
 * They live here and not in a list inside the emitter, and that is the whole of BUG-11: the
 * vocabulary HTML defines belongs with the rest of what HTML defines. The emitter does not
 * learn that \`id\` or \`data-*\` exist; it hands the object literal to a type that does.
 *
 * \`slot\` is deliberately NOT here. Its value is checked against the component's own
 * \`$Slots\`, so declaring it as a plain string would give up exactly the name checking and
 * the completion that make it worth projecting at all.
 */
type $GlobalAttrs = {
  id?: $Scalar;
  class?: $Scalar;
  style?: $Scalar;
  title?: $Scalar;
  lang?: $Scalar;
  dir?: $Scalar;
  hidden?: $Scalar;
  tabindex?: $Scalar;
  part?: $Scalar;
  exportparts?: $Scalar;
  role?: $Scalar;
} & { [k: \`data-\${string}\`]: $Scalar } & { [k: \`aria-\${string}\`]: $Scalar };

declare function $text(v: $Scalar): void;
declare function $attr(v: $Scalar): void;
declare function $attrs<T>(a: T & $GlobalAttrs): void;

/**
 * The PROPS of a component host — what is written with a dot, and nothing else.
 *
 * Without \`$GlobalAttrs\`, and that is the whole of it (BUG-23 §2.1): the literal that
 * carries the props is the one the dot completes against, so intersecting it with HTML's
 * vocabulary made \`<app-badge .|>\` offer \`id\`, \`class\` and \`role\` beside the contract. A
 * plain attribute on the same host still goes to \`$attrs<{}>\`, which is HTML's vocabulary
 * and nothing else.
 */
declare function $props<T>(p: T): void;

/**
 * The REQUIRED keys of \`T\` that \`K\` does not name.
 *
 * \`-?\` strips optionality so \`Pick<T, K>\` can be compared against \`{}\`: a key that is
 * optional makes \`{}\` assignable, so it drops out and only what the author cannot forget
 * survives.
 */
type $RequiredKeys<T> = { [K in keyof T]-?: {} extends Pick<T, K> ? never : K }[keyof T];
type $Missing<T, K> = Pick<T, Exclude<$RequiredKeys<T>, K>>;

/**
 * Completeness, checked APART from the values (BUG-23 §2.1).
 *
 * \`TS2739\` over an object literal is reported on the whole argument — from the \`{\` to the
 * \`}\` — and both of those ends are scaffolding, so Volar mapped the error back nowhere and
 * the missing prop was never reported. Here the argument is a single stretch standing for the
 * tag NAME, which is where the author has to read it anyway.
 */
declare function $required<T, K extends PropertyKey>(rest: $Missing<T, K>): void;
declare function $on<K extends keyof HTMLElementEventMap>(
  type: K, h: (ev: HTMLElementEventMap[K]) => unknown): void;
declare function $section<T extends string>(name: T): void;
declare function $cls(v: boolean): void;
declare function $sty(v: string): void;
declare function $slot(): void;
declare function $intoSlot<T extends string>(name: T): void;
declare function $ref<E extends Element>(): E;

/**
 * The identity of one iteration of a loop (BUG-17 §3.1).
 *
 * \`unknown\` on purpose. Offering is not validating: reconciliation keys a \`Map\`, and in a
 * \`Map\` object identity is a perfectly good key, so \`string | number\` would reject keys
 * that work. \`$key\` exists to open a scope to ask questions in, not to judge the answer.
 *
 * OPTIONAL for the same reason. A \`key (|)\` the author has not finished projects as an empty
 * argument, and that is the one moment the list is wanted; a required parameter would answer
 * it with \`TS2554\` about a stretch nobody typed. The clause being unfinished is already said,
 * once, by \`FUD0541\` — and the compiler is who owns that sentence.
 */
declare function $key(k?: unknown): void;

type $El<T extends string> = T extends keyof HTMLElementTagNameMap
  ? HTMLElementTagNameMap[T]
  : HTMLElement;
`;

/** File name the CLI writes `GLOBALS_DTS` to, and the server mounts it under. */
export const GLOBALS_FILE_NAME = 'fudic-globals.d.ts';
