/**
 * The event handler content attributes of the web platform (SDD-51 §3.6, decision 139).
 *
 * A constant of the compiler, which cannot depend on the editor's HTML service. It is the
 * union of what the standards define — HTML's `GlobalEventHandlers`, `WindowEventHandlers` and
 * `DocumentAndElementEventHandlers`, Pointer Events, Touch Events, CSS Animations and
 * Transitions, Selection, Fullscreen, SVG's animation events — the vendor and legacy names a
 * shipping browser still honours, and every `on*` the editor's HTML data knows. Erring on the
 * long side costs nothing: an `on*` attribute no browser runs is still an attribute nobody
 * meant to write.
 *
 * Lower case: HTML attribute names are case-insensitive, so `ONMOUSEOVER` is `onmouseover`.
 */
export const HTML_EVENT_ATTRIBUTES: ReadonlySet<string> = new Set([
  // GlobalEventHandlers
  'onabort',
  'onauxclick',
  'onbeforeinput',
  'onbeforematch',
  'onbeforetoggle',
  'onblur',
  'oncancel',
  'oncanplay',
  'oncanplaythrough',
  'onchange',
  'onclick',
  'onclose',
  'oncommand',
  'oncontentvisibilityautostatechange',
  'oncontextlost',
  'oncontextmenu',
  'oncontextrestored',
  'oncuechange',
  'ondblclick',
  'ondrag',
  'ondragend',
  'ondragenter',
  'ondragexit',
  'ondragleave',
  'ondragover',
  'ondragstart',
  'ondrop',
  'ondurationchange',
  'onemptied',
  'onended',
  'onerror',
  'onfocus',
  'onformdata',
  'oninput',
  'oninvalid',
  'onkeydown',
  'onkeypress',
  'onkeyup',
  'onload',
  'onloadeddata',
  'onloadedmetadata',
  'onloadstart',
  'onmousedown',
  'onmouseenter',
  'onmouseleave',
  'onmousemove',
  'onmouseout',
  'onmouseover',
  'onmouseup',
  'onpause',
  'onplay',
  'onplaying',
  'onprogress',
  'onratechange',
  'onreset',
  'onresize',
  'onscroll',
  'onscrollend',
  'onscrollsnapchange',
  'onscrollsnapchanging',
  'onsecuritypolicyviolation',
  'onseeked',
  'onseeking',
  'onselect',
  'onslotchange',
  'onstalled',
  'onsubmit',
  'onsuspend',
  'ontimeupdate',
  'ontoggle',
  'onvolumechange',
  'onwaiting',
  'onwheel',
  // WindowEventHandlers
  'onafterprint',
  'onbeforeprint',
  'onbeforeunload',
  'onhashchange',
  'onlanguagechange',
  'onmessage',
  'onmessageerror',
  'onoffline',
  'ononline',
  'onpagehide',
  'onpagereveal',
  'onpageshow',
  'onpageswap',
  'onpopstate',
  'onrejectionhandled',
  'onstorage',
  'onunhandledrejection',
  'onunload',
  // DocumentAndElementEventHandlers
  'oncopy',
  'oncut',
  'onpaste',
  'onbeforecopy',
  'onbeforecut',
  'onbeforepaste',
  // Pointer Events
  'ongotpointercapture',
  'onlostpointercapture',
  'onpointercancel',
  'onpointerdown',
  'onpointerenter',
  'onpointerleave',
  'onpointermove',
  'onpointerout',
  'onpointerover',
  'onpointerrawupdate',
  'onpointerup',
  'onpointerlockchange',
  'onpointerlockerror',
  // Touch Events
  'ontouchcancel',
  'ontouchend',
  'ontouchmove',
  'ontouchstart',
  // CSS Animations and Transitions
  'onanimationcancel',
  'onanimationend',
  'onanimationiteration',
  'onanimationstart',
  'ontransitioncancel',
  'ontransitionend',
  'ontransitionrun',
  'ontransitionstart',
  'onwebkitanimationend',
  'onwebkitanimationiteration',
  'onwebkitanimationstart',
  'onwebkittransitionend',
  // Selection and focus
  'onselectionchange',
  'onselectstart',
  'onfocusin',
  'onfocusout',
  // Fullscreen
  'onfullscreenchange',
  'onfullscreenerror',
  'onwebkitfullscreenchange',
  'onwebkitfullscreenerror',
  // SVG
  'onactivate',
  'onbegin',
  'onend',
  'onrepeat',
  'onzoom',
  // Legacy names a browser or the editor's HTML data still knows
  'onbeforexrselect',
  'onformchange',
  'onforminput',
  'onmousewheel',
  'onreadystatechange',
  'onredo',
  'onsearch',
  'onshow',
  'onundo',
  'onvisibilitychange',
]);

/** Whether an attribute name is one of HTML's inline event handlers. */
export function isNativeEventAttribute(name: string): boolean {
  return HTML_EVENT_ATTRIBUTES.has(name.toLowerCase());
}
